language: php

php:
  - 5.3
  - 5.4

before_script:
   - php composer install
   
script: phpunit --configuration phpunit.xml.dist

notifications:
  email:
    - phansys@gmail.com
    
branches:
  only:
    - v1.9.4.x-dev