language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_install:
  - composer self-update

install:
  - composer install
   
script: 
  - phpunit --configuration phpunit.xml.dist

notifications:
  email:
    - phansys@gmail.com
    
branches:
  only:
    - master
    - v2.0.0-BETA1
    - 2.1
